# Generated by Django 4.0.6 on 2021-09-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portifolio',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
