# Generated by Django 4.0.6 on 2021-10-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0002_alter_portifolio_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portifolio',
            name='image',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
